# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='createdat',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='confirm',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='updatedat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
